name: justcause
channels:
  - r
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - _r-mutex=1.0.0=anacondar_1
  - _tflow_select=2.3.0=mkl
  - absl-py=0.8.0=py37_0
  - apipkg=1.5=py37_0
  - appnope=0.1.0=py37_0
  - arrow-cpp=0.15.0=py37h6477296_1
  - asn1crypto=1.2.0=py37_0
  - astor=0.8.0=py37_0
  - atomicwrites=1.3.0=py37_1
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - backports=1.0=py_2
  - backports.os=0.1.1=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - boost-cpp=1.70.0=hd59e818_1
  - brotli=1.0.7=h0a44026_0
  - bwidget=1.9.11=1
  - bzip2=1.0.8=h1de35cc_0
  - c-ares=1.15.0=h1de35cc_1001
  - ca-certificates=2019.10.16=0
  - cairo=1.14.12=hc4e6be7_4
  - cctools=921=h5ba7a2e_4
  - certifi=2019.9.11=py37_0
  - cffi=1.13.0=py37hb5b8e2f_0
  - chardet=3.0.4=py37_1003
  - clang=9.0.0=h28b9765_1
  - clang_osx-64=9.0.0=h22b1bf0_3
  - clangxx=9.0.0=1
  - clangxx_osx-64=9.0.0=h22b1bf0_3
  - compiler-rt=9.0.0=hce3ea14_0
  - contextlib2=0.6.0=py_0
  - coverage=4.5.4=py37h1de35cc_0
  - coveralls=1.8.2=py_0
  - cryptography=2.8=py37ha12b0ac_0
  - curl=7.65.3=ha441bb4_0
  - cycler=0.10.0=py37_0
  - decorator=4.4.0=py37_1
  - defusedxml=0.6.0=py_0
  - double-conversion=3.1.5=haf313ee_1
  - entrypoints=0.3=py37_0
  - execnet=1.7.1=py_0
  - flake8=3.7.8=py37_1
  - fontconfig=2.13.0=h5d5b041_1
  - freetype=2.9.1=hb4e5f40_0
  - fribidi=1.0.5=h1de35cc_0
  - gast=0.2.2=py37_0
  - gettext=0.19.8.1=h15daf44_3
  - gflags=2.2.2=h0a44026_0
  - gfortran_osx-64=4.8.5=h22b1bf0_8
  - glib=2.56.2=hd9629dc_0
  - glog=0.4.0=h0a44026_0
  - google-pasta=0.1.7=py_0
  - graphite2=1.3.13=h2098e52_0
  - grpc-cpp=1.23.0=h5c95ec2_0
  - grpcio=1.16.1=py37h044775b_1
  - gsl=2.4=h1de35cc_4
  - h5py=2.9.0=py37h3134771_0
  - harfbuzz=1.8.8=hb8d4a28_0
  - hdf5=1.10.4=hfa1e0ec_0
  - icu=58.2=h4b95b61_1
  - idna=2.8=py37_0
  - importlib_metadata=0.23=py37_0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.2=py37h39e3cac_0
  - ipython=7.8.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - joblib=0.13.2=py37_0
  - jpeg=9c=h1de35cc_1001
  - json5=0.8.5=py_0
  - jsonschema=3.1.1=py37_0
  - jupyter_client=5.3.4=py37_0
  - jupyter_core=4.6.0=py37_0
  - jupyterlab=1.1.4=pyhf63ae98_0
  - jupyterlab_server=1.0.6=py_0
  - keras=2.2.4=0
  - keras-applications=1.0.8=py_0
  - keras-base=2.2.4=py37_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py37h0a44026_0
  - krb5=1.16.1=hddcf347_7
  - ld64=409.12=h3c32e8a_4
  - libcurl=7.65.3=h051b688_0
  - libcxx=9.0.0=h89e68fa_1
  - libedit=3.1.20181209=hb402a30_0
  - libevent=2.1.10=h212c5bf_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libllvm9=9.0.0=h770b8ee_2
  - libpng=1.6.37=ha441bb4_0
  - libprotobuf=3.8.0=hd9629dc_0
  - libsodium=1.0.16=h3efe00b_0
  - libssh2=1.8.2=ha12b0ac_0
  - libtiff=4.0.10=h3527a1b_1004
  - libxml2=2.9.9=hf6e021a_1
  - llvm-openmp=4.0.1=hcfea43d_1
  - lz4-c=1.8.3=h6de7cb9_1001
  - make=4.2.1=h3efe00b_1
  - markdown=3.1.1=py37_0
  - markupsafe=1.1.1=py37h1de35cc_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.14=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - mock=3.0.5=py37_0
  - more-itertools=7.2.0=py37_0
  - nbconvert=5.6.0=py37_1
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=h0a44026_1
  - notebook=6.0.1=py37_0
  - numpy=1.17.2=py37h99e6662_0
  - numpy-base=1.17.2=py37h6575580_0
  - openssl=1.1.1d=h1de35cc_3
  - opt_einsum=3.1.0=py_0
  - packaging=19.2=py_0
  - pandas=0.25.2=py37h0a44026_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - pango=1.42.4=h060686c_0
  - parquet-cpp=1.5.1=2
  - parso=0.5.1=py_0
  - path.py=12.0.1=py_0
  - patsy=0.5.1=py37_0
  - pcre=8.43=h0a44026_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h1de35cc_0
  - pluggy=0.13.0=py37_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - protobuf=3.8.0=py37h0a44026_0
  - ptyprocess=0.6.0=py37_0
  - py=1.8.0=py37_0
  - pycodestyle=2.5.0=py37_0
  - pycparser=2.19=py37_0
  - pyflakes=2.1.1=py37_0
  - pygments=2.4.2=py_0
  - pymongo=3.9.0=py37h0a44026_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.2=py_0
  - pyrsistent=0.15.4=py37h1de35cc_0
  - pysocks=1.7.1=py37_0
  - pytest=5.2.1=py37_0
  - pytest-cov=2.7.1=py_0
  - pytest-fixture-config=1.7.0=py_0
  - pytest-shutil=1.7.0=py_0
  - pytest-virtualenv=1.7.0=py_0
  - python=3.7.4=h359304d_1
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.3=py_0
  - pyyaml=5.1.2=py37h1de35cc_0
  - pyzmq=18.1.0=py37h0a44026_0
  - r-assertthat=0.2.1=r36h6115d3f_0
  - r-base=3.6.1=hcb44179_1
  - r-bh=1.69.0_1=r36h6115d3f_0
  - r-bit=1.1_14=r36h46e59ec_0
  - r-bit64=0.9_7=r36h46e59ec_0
  - r-blob=1.1.1=r36h6115d3f_0
  - r-cli=1.1.0=r36h6115d3f_0
  - r-crayon=1.3.4=r36h6115d3f_0
  - r-dbi=1.0.0=r36h6115d3f_0
  - r-dbplyr=1.4.0=r36h6115d3f_0
  - r-digest=0.6.18=r36h46e59ec_0
  - r-dplyr=0.8.0.1=r36h466af19_0
  - r-fansi=0.4.0=r36h46e59ec_0
  - r-glue=1.3.1=r36h46e59ec_0
  - r-magrittr=1.5=r36h6115d3f_4
  - r-memoise=1.1.0=r36h6115d3f_0
  - r-pillar=1.3.1=r36h6115d3f_0
  - r-pkgconfig=2.0.2=r36h6115d3f_0
  - r-plogr=0.2.0=r36h6115d3f_0
  - r-prettyunits=1.0.2=r36h6115d3f_0
  - r-purrr=0.3.2=r36h46e59ec_0
  - r-r6=2.4.0=r36h6115d3f_0
  - r-rcpp=1.0.1=r36h466af19_0
  - r-rlang=0.3.4=r36h46e59ec_0
  - r-rsqlite=2.1.1=r36h466af19_0
  - r-tibble=2.1.1=r36h46e59ec_0
  - r-tidyselect=0.2.5=r36h466af19_0
  - r-utf8=1.1.4=r36h46e59ec_0
  - re2=2019.08.01=h0a44026_0
  - readline=7.0=h1de35cc_5
  - requests=2.22.0=py37_0
  - rpy2=2.9.4=py37r36h1d22016_0
  - seaborn=0.9.0=py37_0
  - send2trash=1.5.0=py37_0
  - setuptools=41.4.0=py37_0
  - six=1.12.0=py37_0
  - snappy=1.1.7=he62c110_3
  - sqlite=3.30.1=ha441bb4_0
  - statsmodels=0.10.1=py37h1d22016_0
  - tapi=1000.10.8=h770b8ee_3
  - tensorboard=2.0.0=pyhb230dea_0
  - tensorflow=2.0.0=mkl_py37hda344b4_0
  - tensorflow-base=2.0.0=mkl_py37h66b1bf0_0
  - tensorflow-estimator=2.0.0=pyh2649769_0
  - termcolor=1.1.0=py37_1
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py37_0
  - thrift-cpp=0.12.0=h874095a_1004
  - tk=8.6.8=ha441bb4_0
  - tktable=2.10=h1de35cc_0
  - tornado=6.0.3=py37h1de35cc_0
  - traitlets=4.3.3=py37_0
  - uriparser=0.9.3=h6de7cb9_1
  - urllib3=1.24.2=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - wrapt=1.11.2=py37h1de35cc_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.3.1=h0a44026_3
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.3=he7fca8b_0
  - pip:
    - aspy-yaml==1.3.0
    - causalml==0.4.0
    - cfgv==2.0.1
    - colorama==0.4.1
    - cython==0.29.13
    - dill==0.3.1.1
    - docopt==0.6.2
    - eli5==0.10.1
    - future==0.18.1
    - gitdb2==2.0.6
    - gitpython==3.0.4
    - identify==1.4.7
    - jsonpickle==0.9.6
    - lightgbm==2.3.0
    - matplotlib==2.2.4
    - munch==2.3.2
    - nodeenv==1.3.3
    - ply==3.11
    - pre-commit==1.18.3
    - py-cpuinfo==5.0.0
    - pyarrow==0.14.1
    - pydotplus==2.0.2
    - python-graphviz==0.13
    - sacred==0.8.0
    - scikit-learn==0.20.3
    - scipy==1.2.2
    - shap==0.31.0
    - smmap2==2.0.5
    - tabulate==0.8.5
    - toml==0.10.0
    - tqdm==4.36.1
    - virtualenv==16.7.5
    - xgboost==0.82
prefix: /Users/MaximilianFranz/anaconda3/envs/justcause
