# This environment is for developers of JustCause and includes
# more dependencies than necessary if you just want to use it.
name: justcause
channels:
  - r
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - scipy
  - pandas
  - scikit-learn
  - pip
  - seaborn
  - r-base
  - rpy2
  - seaborn
  - tensorflow
  - keras
  - pymongo
  - pyarrow
  # for development below here
  - pytest
  - pytest-cov
  - pytest-virtualenv
  - coverage
  - coveralls
  - flake8
  - pip:
      - sacred
      - pre-commit
